### ISSUE TITLE
Could you please provide some documents or explanation of codes?

### ISSUE THREAD

**Issue by WilliamWangPeng** [masotrix/CudaRayTracer#1]
Hi dear author,  
    It's a great honor to open one issue here, truly honor.  I just begin to learn computer graphics and have compiled your program successfully, but it is hard for me to read the codes, could you please provide some explanation or PPT or papers about the code to me?   👍 

thank you  
Best Regards with kindness  
William

**Comment by masotrix** [comment]
Hi William, yes of course
I did this a long time ago when I did not know about papers, maybe I could have done one with this project haha
Here is a PPT which is in Spanish but I guess it is quite easy to infer what it means https://github.com/masotrix/ProjectsCurriculum/blob/master/GPU%20Raytracing.pdf
Best regards

**Comment by WilliamWangPeng** [comment]
> Hi William, yes of course
> I did this a long time ago when I did not know about papers, maybe I could have done one with this project haha
> Here is a PPT which is in Spanish but I guess it is quite easy to infer what it means https://github.com/masotrix/ProjectsCurriculum/blob/master/GPU%20Raytracing.pdf
> Best regards

thank you dear @masotrix  
    It's very nice of you, I will try to read the codes following the main document you have given me,  It's such a gift in the Teachers' Day 👍   

thank you  
best regards  
William
